# -*- coding: utf-8 -*-
"""Base(cancer).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SznVwP9b2TDY-WwMkXnXbtUfFNUanPly
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np

file_path= r"/content/drive/MyDrive/Algoritmia y Programación/Colab Notebooks/breast_cancer_bd.csv"
data = pd.read_csv(file_path)
data

data.info()

data.describe()

print(data.isnull().sum())

data.duplicated()

print(data.duplicated().sum())

print(data.isna().sum())

data

"""Transformar la columna Bare Nuclei de objects a numérica; (Algunos de sus datos estan asignados como "?", entoces se cambiaran por la mediana."""

data['Bare Nuclei'] = data['Bare Nuclei'].replace('?', np.nan)

data

data['Bare Nuclei'] = pd.to_numeric(data['Bare Nuclei'])

data.isna().sum()

data["Bare Nuclei"].fillna(data["Bare Nuclei"].median(), inplace=True)

data.info()
data.describe()

data

"""Se Bucó más incoherencias como valores fuera del intervalo (1,10) en la mayoria de columnas."""

data[data['Bare Nuclei']>10]

data[data['Clump Thickness']==0]

data[data['Clump Thickness']>10]

data[data['Uniformity of Cell Size']==0]

data[data['Uniformity of Cell Size']>10]

data[data['Uniformity of Cell Shape']==0]

data[data['Uniformity of Cell Shape']>10]

data[data['Marginal Adhesion']==0]

data[data['Marginal Adhesion']>10]

data[data['Single Epithelial Cell Size']==0]

data[data['Single Epithelial Cell Size']>10]

data[data['Bland Chromatin']==0]

data[data['Bland Chromatin']>10]

data[data['Normal Nucleoli']==0]

data[data['Normal Nucleoli']>10]

data[data['Mitoses']==0]

data[data['Mitoses']>10]

"""No se encontraron más datos incoherentes para esta base, por tanto ya esta limpia."""

