# -*- coding: utf-8 -*-
"""Base(Diabetes).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TKZzE8gBOnk-1l4xK6rGJ-YUo6J4xvjU
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

file_path= r"/content/drive/MyDrive/Algoritmia y Programación/Colab Notebooks/Diabetes.csv"
data = pd.read_csv(file_path)
data

data.info()

data.describe()

print(data.isna().sum())

print(data.isnull().sum())

print(data.duplicated())

print(data.duplicated().sum())

data

"""Se Buscan Datos Incoherentes"""

data[data['BMI'] <= 0]

data

data[data['Insulin'] <= 0]

data[data['Glucose'] <= 0]

data[data['BloodPressure'] <= 0]

data[data['SkinThickness'] <= 0]

"""Se hace una lista con las columnas que contienen esos datos"""

ccdi=["Glucose", "Insulin", "BMI", "SkinThickness", "BloodPressure"]

data[ccdi].min()

"""Reemplazamos los 0, por NaN, para sacar la suma"""

data[ccdi] = data[ccdi].replace(0, np.nan)

data

data.isna().sum()

"""Reemplazo de los datos incoherentes por la mediana, ya que en los datos médicos es la más eficiente"""

for col in ccdi:
    data[col] = data[col].fillna(data[col].median())

data

data.max()

data[data['SkinThickness'] > 65]

data=data[data['SkinThickness'] <65]

data[data['BloodPressure'] > 120]

data=data[data['BloodPressure'] <= 120]

data

data[data['Insulin'] > 276]

data["Insulin"] = data["Insulin"].mask(data["Insulin"] > 276, np.nan)

data['Insulin'].describe()
data['Insulin'].isna().sum()

data

data["Insulin"].fillna(data["Insulin"].median(), inplace=True)

data

data[data['BMI'] > 60]

data=data[data['BMI'] < 60]

data.max()